"""Add CandidateDemographics

Revision ID: 0adf9af3b949
Revises: 2ff6c2df4d39
Create Date: 2026-08-19 09:10:07.562247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0adf9af3b949'
down_revision: Union[str, Sequence[str], None] = '2ff6c2df4d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('race_ethnicity', sa.String(), nullable=True),
    sa.Column('veteran_status', sa.String(), nullable=True),
    sa.Column('disability_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidate_demographics_id'), 'candidate_demographics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_demographics_id'), table_name='candidate_demographics')
    op.drop_table('candidate_demographics')
    # ### end Alembic commands ###
