"""Add enrichment columns

Revision ID: 2ff6c2df4d39
Revises: 4c56a677dbd3
Create Date: 2026-08-19 09:04:34.564244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff6c2df4d39'
down_revision: Union[str, Sequence[str], None] = '4c56a677dbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('external_evidence', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('engineering_quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'engineering_quality_score')
    op.drop_column('candidates', 'external_evidence')
    op.drop_column('candidates', 'social_links')
    # ### end Alembic commands ###
