"""Add staleness tracking columns

Revision ID: 942d4d355541
Revises: 0adf9af3b949
Create Date: 2026-08-19 09:15:10.958093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942d4d355541'
down_revision: Union[str, Sequence[str], None] = '0adf9af3b949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('last_enriched_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('staleness_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'staleness_score')
    op.drop_column('candidates', 'last_enriched_at')
    # ### end Alembic commands ###
