"""Add validation_status

Revision ID: da7c8fe0dd16
Revises: c06622296907
Create Date: 2026-08-19 09:38:05.556875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7c8fe0dd16'
down_revision: Union[str, Sequence[str], None] = 'c06622296907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_evidence', sa.Column('validation_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_evidence', 'validation_status')
    # ### end Alembic commands ###
